vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
